const { buildSitemap } = require('../utils/buildSitemap');

/**
 * The sitemap, served live.
 *
 * WHY IT IS AN ENDPOINT AND NOT A FILE ANY MORE
 *   The committed frontend/public/sitemap.xml was written by a script somebody
 *   had to remember to run. On 7 September 2026 the deployed file was a week
 *   old and Google's copy of it was NINE MONTHS old - six URLs against a
 *   catalogue of ninety-two. Nothing failed and nothing warned; the shop simply
 *   was not in the index.
 *
 *   A file that has to be regenerated by hand is a promise the shop keeps only
 *   as long as somebody remembers. This is generated from the same database the
 *   shop sells from, so a product added at midnight is in the sitemap at
 *   midnight.
 *
 * WHY IT IS PUBLIC
 *   Google fetches it as an anonymous crawler, and everything in it is a public
 *   URL anyway. Nothing about sellers, orders or stock levels goes near it -
 *   only which pages exist.
 */
exports.sitemap = async (req, res) => {
  try {
    const { xml } = await buildSitemap();

    res.set('Content-Type', 'application/xml; charset=utf-8');
    /*
     * An hour. Crawlers re-fetch a sitemap far more often than the catalogue
     * changes, and every fetch is two database queries. An hour old is still
     * fresher than the file this replaces ever managed.
     */
    res.set('Cache-Control', 'public, max-age=3600');
    return res.send(xml);
  } catch (error) {
    console.error('SITEMAP ERROR:', error.message);
    /*
     * 503 and not 200-with-an-error-body. A crawler that receives a valid but
     * EMPTY sitemap concludes the site has no pages and can drop what it has
     * already indexed; one that receives a 503 simply comes back later.
     */
    return res.status(503).send('<?xml version="1.0"?><error>Sitemap unavailable</error>');
  }
};
